name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: clang++ text2table.cpp -o text2table
    - name: test 
      run: ./text2table tests/in/test1.txt output.txt && cmp output.txt tests/out/test1.txt
    - name: Tidy
      run: clang-tidy text2table.cpp

